DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Models/Brand.cs
namespace DoAnLapTrinhWed_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web;

    [Table("Brand")]
    public partial class Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            Products = new HashSet<Product>();
        }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
        public int BrandId { get; set; }

        [StringLength(50)]
        public string Name { get; set; }

        [StringLength(50)]
        public string Avartar { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Areas/Admin/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using DoAnLapTrinhWed_2.Models;
using PagedList;

namespace DoAnLapTrinhWed_2.Areas.Admin.Controllers
{
    public class BrandsController : Controller
    {
        private ModelLinhKienContext context = new ModelLinhKienContext();

        // GET: Admin/Brands
        [Authorize(Roles = "Admin")]
        public ActionResult Index(string currentFilter, string SearchString, int? page)
        {
            var listBrand = new List<Brand>();
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }
            if (!String.IsNullOrEmpty(SearchString))
            {
                listBrand = context.Brands.Where(n => n.Name.Contains(SearchString)).ToList();
            }
            else
            {
                listBrand = context.Brands.ToList();
            }
            ViewBag.CurrentFilter = SearchString;
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            listBrand = listBrand.OrderBy(n => n.BrandId).ToList();
            return View(listBrand.ToPagedList(pageNumber, pageSize));

        }

        // GET: Admin/Brands/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = context.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: Admin/Brands/Create
        public ActionResult Create()
        {
            var context = new ModelLinhKienContext();
            return View();
        }

        // POST: Admin/Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Brand brand)
        {
            var context = new ModelLinhKienContext();

            if (ModelState.IsValid)
            {
                if (brand.ImageFile != null && brand.ImageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(brand.ImageFile.FileName);
                    var filePath = Path.Combine(Server.MapPath("~/Content/images/items/"), fileName);
                    brand.ImageFile.SaveAs(filePath);
                    brand.Avartar = "" + fileName;
                }
                context.Brands.Add(brand);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("Create");
        }

        // GET: Admin/Brands/Edit/5
        public ActionResult Edit(int id)
        {
            ModelLinhKienContext context = new ModelLinhKienContext();
            Brand firstBrand = context.Brands.FirstOrDefault(p => p.BrandId == id);
            if (firstBrand != null)
            {
                return View(firstBrand);
            }
            return Content("Không tìm thấy id");
        }

        // POST: Admin/Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Brand brand)
        {
            ModelLinhKienContext context = new ModelLinhKienContext();
            Brand firstBrand = context.Brands.FirstOrDefault(p => p.BrandId == brand.BrandId);
            if (firstBrand == null)
            {
                return HttpNotFound("Không tìm thấy mã sách này!");
            }
            else
            {
                if (brand.ImageFile != null && brand.ImageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(brand.ImageFile.FileName);
                    var filePath = Path.Combine(Server.MapPath("~/Content/images/items/"), fileName);
                    brand.ImageFile.SaveAs(filePath);
                    brand.Avartar = "" + fileName;
                }
                firstBrand.Name = brand.Name;
                firstBrand.Avartar = brand.Avartar;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        // GET: Admin/Brands/Delete/5
        public ActionResult Delete(int? id)
        {
            ModelLinhKienContext context = new ModelLinhKienContext();
            Brand firstBrand = context.Brands.FirstOrDefault(p => p.BrandId == id);
            if (firstBrand != null)
            {
                return View(firstBrand);
            }
            return Content("Không tìm thấy id");
        }

        // POST: Admin/Brands/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            ModelLinhKienContext context = new ModelLinhKienContext();
            Brand firstBrand = context.Brands.FirstOrDefault(p => p.BrandId == id);
            if (firstBrand == null)
            {
                return HttpNotFound("Không tìm thấy linh kiện này!");
            }
            else
            {
                context.Brands.Remove(firstBrand);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Areas/Admin/Views/Brands/Create.cshtml
@model DoAnLapTrinhWed_2.Models.Brand

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Thêm thương hiệu</h2>

@using (Html.BeginForm("Create", "Brands", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avartar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Avartar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Avartar, "", new { @class = "text-danger" })*@
                <input type="file" name="ImageFile" required class="form-control" accept=".png, .jpg, .jpeg" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Areas/Admin/Views/Brands/Delete.cshtml
@model DoAnLapTrinhWed_2.Models.Brand

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Xóa</h2>

<h3>Bạn có muốn xóa thương hiệu này không?</h3>
<div>
    <h4>Brand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avartar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avartar)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Areas/Admin/Views/Brands/Details.cshtml
@model DoAnLapTrinhWed_2.Models.Brand

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Brand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avartar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avartar)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BrandId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Areas/Admin/Views/Brands/Edit.cshtml
@model DoAnLapTrinhWed_2.Models.Brand

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Sửa thương hiệu</h2>

@using (Html.BeginForm("Edit", "Brands", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BrandId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avartar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Avartar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Avartar, "", new { @class = "text-danger" })*@
                <input type="file" name="ImageFile" required class="form-control" accept=".png, .jpg, .jpeg" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Areas/Admin/Views/Brands/Index.cshtml
@using PagedList;
@using PagedList.Mvc;


@model PagedList.IPagedList<DoAnLapTrinhWed_2.Models.Brand>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<style>
    .pagination {
        display: inline-block;
        padding-left: 0;
        margin: 20px 0;
        border-radius: 4px;
    }

        .pagination > li {
            display: inline;
        }

            .pagination > li > a,
            .pagination > li > span {
                position: relative;
                float: left;
                padding: 6px 12px;
                margin-left: -1px;
                line-height: 1.428571429;
                text-decoration: none;
                background-color: #ffffff;
                border: 1px solid #dddddd;
            }

            .pagination > li:first-child > a,
            .pagination > li:first-child > span {
                margin-left: 0;
                border-bottom-left-radius: 4px;
                border-top-left-radius: 4px;
            }

            .pagination > li:last-child > a,
            .pagination > li:last-child > span {
                border-top-right-radius: 4px;
                border-bottom-right-radius: 4px;
            }

            .pagination > li > a:hover,
            .pagination > li > span:hover,
            .pagination > li > a:focus,
            .pagination > li > span:focus {
                background-color: #eeeeee;
            }

        .pagination > .active > a,
        .pagination > .active > span,
        .pagination > .active > a:hover,
        .pagination > .active > span:hover,
        .pagination > .active > a:focus,
        .pagination > .active > span:focus {
            z-index: 2;
            color: #ffffff;
            cursor: default;
            background-color: #428bca;
            border-color: #428bca;
        }

        .pagination > .disabled > span,
        .pagination > .disabled > a,
        .pagination > .disabled > a:hover,
        .pagination > .disabled > a:focus {
            color: #999999;
            cursor: not-allowed;
            background-color: #ffffff;
            border-color: #dddddd;
        }

    .pagination-lg > li > a,
    .pagination-lg > li > span {
        padding: 10px 16px;
        font-size: 18px;
    }

    .pagination-lg > li:first-child > a,
    .pagination-lg > li:first-child > span {
        border-bottom-left-radius: 6px;
        border-top-left-radius: 6px;
    }

    .pagination-lg > li:last-child > a,
    .pagination-lg > li:last-child > span {
        border-top-right-radius: 6px;
        border-bottom-right-radius: 6px;
    }

    .pagination-sm > li > a,
    .pagination-sm > li > span {
        padding: 5px 10px;
        font-size: 12px;
    }

    .pagination-sm > li:first-child > a,
    .pagination-sm > li:first-child > span {
        border-bottom-left-radius: 3px;
        border-top-left-radius: 3px;
    }

    .pagination-sm > li:last-child > a,
    .pagination-sm > li:last-child > span {
        border-top-right-radius: 3px;
        border-bottom-right-radius: 3px;
    }

    .pager {
        padding-left: 0;
        margin: 20px 0;
        text-align: center;
        list-style: none;
    }

        .pager:before,
        .pager:after {
            display: table;
            content: " ";
        }

        .pager:after {
            clear: both;
        }

        .pager:before,
        .pager:after {
            display: table;
            content: " ";
        }

        .pager:after {
            clear: both;
        }

        .pager li {
            display: inline;
        }

            .pager li > a,
            .pager li > span {
                display: inline-block;
                padding: 5px 14px;
                background-color: #ffffff;
                border: 1px solid #dddddd;
                border-radius: 15px;
            }

                .pager li > a:hover,
                .pager li > a:focus {
                    text-decoration: none;
                    background-color: #eeeeee;
                }

        .pager .next > a,
        .pager .next > span {
            float: right;
        }

        .pager .previous > a,
        .pager .previous > span {
            float: left;
        }

        .pager .disabled > a,
        .pager .disabled > a:hover,
        .pager .disabled > a:focus,
        .pager .disabled > span {
            color: #999999;
            cursor: not-allowed;
            background-color: #ffffff;
        }
</style>

<h2>Quane lý danh mục</h2>

<button onclick="location.href='@Url.Action("Create", "Brands")'" class="btn btn-primary">Create New</button>

<style>
    .search-container {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-bottom: 20px;
        padding: 20px;
        background-color: #f1f1f1;
        border-radius: 5px;
    }

        .search-container input[type=text] {
            width: 60%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }

        .search-container input[type=submit] {
            background-color: #4CAF50;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }

            .search-container input[type=submit]:hover {
                background-color: #45a049;
            }
</style>

@using (Html.BeginForm("Index", "Brands", FormMethod.Get))
{
   @*<p>
    Tìm tên sản phẩm: @Html.TextBox("SearchString", ViewBag.Currenfilter as string, new { @class = "search-box" })
    <input type="submit" value="Tìm kiếm" class="search-button" />
   </p>*@
    <div class="search-container">
    <form action="/search" method="get">
        <label for="SearchString">Tìm tên sản phẩm:</label>
        <input type="text" id="SearchString" name="SearchString" placeholder="Tìm tên thương hiệu...">
        <input type="submit" value="Tìm kiếm">
    </form>
    </div>
}


<table class="table" id="tblBrands">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Avartar)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Avartar)*@
                <img src="~/Content/images/items/@item.Avartar" width="100" height="100" />
            </td>
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { id = item.BrandId }) |
                @Html.ActionLink("Details", "Details", new { id = item.BrandId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.BrandId })
            </td>*@
            <td>
                <button onclick="location.href='@Url.Action("Edit", "Brands", new { id = item.BrandId })'" class="btn btn-primary">Sửa</button>
                <button onclick="location.href='@Url.Action("Details", "Brands", new { id = item.BrandId })'" class="btn btn-secondary">Chi tiết</button>
                <button onclick="location.href='@Url.Action("Delete", "Brands", new { id = item.BrandId })'" class="btn btn-danger">Xóa</button>
            </td>
        </tr>
    }

</table>


Trang @(Model.PageCount <Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }),
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
    {
        HttpMethod = "GET",
        UpdateTargetId = "tblBrands"
    })) 