DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using DoAnLapTrinhWed_2.Models;
using PagedList;

namespace DoAnLapTrinhWed_2.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
       
        private ModelLinhKienContext context = new ModelLinhKienContext();

        // GET: Admin/Products
        [Authorize(Roles = "Admin")]
        public ActionResult Index(string currentFilter,string SearchString,int? page)
        {
            //var products = context.Products.Where(n=>n.Name.Contains(SearchString)).ToList();
            var listProduct = new List<Product>();
            if(SearchString != null)
            {
                page = 1;
            }
            else
            {   
                SearchString = currentFilter;
            }
            if (!String.IsNullOrEmpty(SearchString))
            {
                listProduct = context.Products.Where(n => n.Name.Contains(SearchString)).ToList();
            }
            else
            {
                listProduct = context.Products.ToList();
            }
            ViewBag.CurrentFilter = SearchString;
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            listProduct = listProduct.OrderBy(n => n.Id).ToList();
            return View(listProduct.ToPagedList(pageNumber, pageSize));
           
        }

        // GET: Admin/Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = context.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Admin/Products/Create
        public ActionResult Create()
        {
            var context = new ModelLinhKienContext();
            ViewBag.ListBrand = context.Brands.ToList();
            ViewBag.ListNCC = context.NCCs.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
            var context = new ModelLinhKienContext();
            if (ModelState.IsValid)
            {
                string allfile = "";
                string[]split= null; ;
                foreach (var file in product.ImageFile)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var filePath = Path.Combine(Server.MapPath("~/Content/images/items/"), fileName);
                        file.SaveAs(filePath);
                        allfile += "|" +fileName ;
                    }
                    
                }
                split = allfile.Split('|');
                product.Avartar = "" + split[1];
                product.Avartar1 = "" + split[2];
                product.Avartar2 = "" + split[3];
                product.Avartar3 = "" + split[4];
                context.Products.Add(product);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("Create");
        }

        // GET: Admin/Products/Edit/5
        public ActionResult Edit(int id)
        {
            ModelLinhKienContext context = new ModelLinhKienContext();
            ViewBag.ListNCC = context.NCCs.ToList();
            ViewBag.ListBrand = context.Brands.ToList();
            Product firstBook = context.Products.FirstOrDefault(p => p.Id == id);
            if (firstBook != null)
            {
                return View(firstBook);
            }
            return Content("Không tìm thấy id");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product)
        {
            var context = new ModelLinhKienContext();
            Product firstProduct = context.Products.FirstOrDefault(p => p.Id == product.Id);
            if (firstProduct == null)
            {
                return HttpNotFound("Không tìm thấy linh kiện này!");
            }
            else
            {
                string allfile = "";
                string[] split = null; ;
                foreach (var file in product.ImageFile)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var filePath = Path.Combine(Server.MapPath("~/Content/images/items/"), fileName);
                        file.SaveAs(filePath);
                        allfile += "|" + fileName;
                    }

                }
                split = allfile.Split('|');
                product.Avartar = "" + split[1];
                product.Avartar1 = "" + split[2];
                product.Avartar2 = "" + split[3];
                product.Avartar3 = "" + split[4];
                firstProduct.Name = product.Name;
                firstProduct.Avartar = product.Avartar;
                firstProduct.Avartar1 = product.Avartar1;
                firstProduct.Avartar2 = product.Avartar2;
                firstProduct.Avartar3 = product.Avartar3;
                firstProduct.ShortDes = product.ShortDes;
                firstProduct.Price = product.Price;
                firstProduct.TinhTrang = product.TinhTrang;
                firstProduct.BaoHanh = product.BaoHanh;
                firstProduct.BrandId = product.BrandId;
                firstProduct.NCCId = product.NCCId;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        // GET: Admin/Products/Delete/5
        public ActionResult Delete(int id)
        {
            ModelLinhKienContext context = new ModelLinhKienContext();
            Product firstProduct = context.Products.FirstOrDefault(p => p.Id == id);
            if (firstProduct != null)
            {
                return View(firstProduct);
            }
            return Content("Không tìm thấy id");
        }

        // POST: Admin/Products/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Product deleteProduct)
        {
            ModelLinhKienContext context = new ModelLinhKienContext();
            Product firstProduct = context.Products.FirstOrDefault(p => p.Id == deleteProduct.Id);
            if (firstProduct == null)
            {
                return HttpNotFound("Không tìm thấy linh kiện này!");
            }
            else
            {
                context.Products.Remove(firstProduct);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnLapTrinhWed_2.Models;

namespace DoAnLapTrinhWed_2.Controllers
{
    public class ProductsController : Controller
    {
        private ModelLinhKienContext context = new ModelLinhKienContext();

        // GET: Products
        public ActionResult Index()
        {
            return View(context.Products.ToList());
        }
        public ActionResult GetProducts(int? id)
        {
            return View("Index", context.Products.Where(p => p.BrandId == id).ToList());
        }
        public ActionResult GetBrand()
        {
            ModelLinhKienContext context = new ModelLinhKienContext();
            var listbrand = context.Brands.ToList();
            return PartialView(listbrand);
        }
        public ActionResult GetBrand2()
        {
            ModelLinhKienContext context = new ModelLinhKienContext();
            var listbrand = context.Brands.ToList();
            return PartialView(listbrand);
        }
        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = context.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.BrandId = new SelectList(context.Brands, "BrandId", "Name");
            ViewBag.NCCId = new SelectList(context.NCCs, "NccId", "TenNCC");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Avartar,Avartar1,Avartar2,Avartar3,ShortDes,FullDescription,Price,PriceDiscount,Slug,Deleted,ShowOnHomePage,DisplayOrder,TinhTrang,BaoHanh,CreatedOnUtc,UpdateOnUtc,BrandId,NCCId")] Product product)
        {
            if (ModelState.IsValid)
            {
                context.Products.Add(product);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrandId = new SelectList(context.Brands, "BrandId", "Name", product.BrandId);
            ViewBag.NCCId = new SelectList(context.NCCs, "NccId", "TenNCC", product.NCCId);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = context.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.BrandId = new SelectList(context.Brands, "BrandId", "Name", product.BrandId);
            ViewBag.NCCId = new SelectList(context.NCCs, "NccId", "TenNCC", product.NCCId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Avartar,Avartar1,Avartar2,Avartar3,ShortDes,FullDescription,Price,PriceDiscount,Slug,Deleted,ShowOnHomePage,DisplayOrder,TinhTrang,BaoHanh,CreatedOnUtc,UpdateOnUtc,BrandId,NCCId")] Product product)
        {
            if (ModelState.IsValid)
            {
                context.Entry(product).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BrandId = new SelectList(context.Brands, "BrandId", "Name", product.BrandId);
            ViewBag.NCCId = new SelectList(context.NCCs, "NccId", "TenNCC", product.NCCId);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = context.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = context.Products.Find(id);
            context.Products.Remove(product);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Controllers/ShoppingCartController.cs
using DoAnLapTrinhWed_2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace DoAnLapTrinhWed_2.Controllers
{
    public class ShoppingCartController : Controller
    {
        ModelLinhKienContext context = new ModelLinhKienContext();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            //return View((List<CartModel>)Session["cart"]);
            List<CartModel> cart = ((List<CartModel>)Session["cart"]);
            if(cart == null)
            {
                cart = new List<CartModel>();
                Session["cart"] = cart;
            }
            else
            {
                ViewBag.TongTien = cart.Sum(p => p.Quantity * p.Product.Price);
            }
            return View(cart);
        }
        public ActionResult AddToCart(int id,int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = context.Products.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { Product = context.Products.Find(id), Quantity = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.Id.Equals(id))
                    return i;
            return -1;
        }
        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["Cart"];
            li.RemoveAll(x => x.Product.Id == Id);

            Session["Cart"] = li;
            Session["Count"] = Convert.ToInt32(Session["Count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
        [HttpPost]
        public ActionResult UpdateProductQuantity(int id, int quantity)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            CartModel cartItem = cart.FirstOrDefault(p => p.Product.Id == id);
            if (cartItem != null)
            {
                cartItem.Quantity = quantity;
            }

            Session["cart"] = cart;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
    }
}

DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Views/Products/Delete.cshtml
@model DoAnLapTrinhWed_2.Models.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NCC.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NCC.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avartar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avartar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avartar1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avartar1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avartar2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avartar2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avartar3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avartar3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortDes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceDiscount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceDiscount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Slug)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slug)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShowOnHomePage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShowOnHomePage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisplayOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisplayOrder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TinhTrang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TinhTrang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BaoHanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BaoHanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOnUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOnUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateOnUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateOnUtc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Views/Products/Details.cshtml
@model DoAnLapTrinhWed_2.Models.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

<script type="text/javascript">
    $(function () {
        $("#addtocart").click(function () {
            var model = {};
            //lấy id sản phẩm
            model.Id = @Model.Id;
            // lấy số lượng đặt hàng
            model.Quantity = $("#ipQuantity").val();
            debugger;
            $.ajax({
                type: "POST",
                url: '@Url.Action("AddToCart", "ShoppingCart")',
                data:  JSON.stringify(model) ,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function () {
                    alert("Thêm giỏ hàng thành công!")
                    $('#CartCount').text(@Session["count"] + 1);
                },
                error: function () {
                    alert("Lỗi trong khi thêm vào giỏ hàng!");
                }
            });
            return false;
        });
    });
    $(document).ready(function () {
        // Bắt sự kiện click vào hình phụ
        $('.item-thumb').click(function (e) {
            e.preventDefault();
            // Lấy đường dẫn của hình ảnh mới
            var newSrc = $(this).find('img').attr('src');
            // Đổi hình ảnh chính
            $('.img-big-wrap img').attr('src', newSrc);
            // Thêm lớp active cho hình phụ hiện tại
            $('.item-thumb').removeClass('thumb-main');
            $(this).addClass('thumb-main');
        });
    });
</script>

<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Website title - bootstrap html template</title>

    <link href="images/favicon.ico" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="css/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="css/ui.css" rel="stylesheet" type="text/css" />
    <link href="css/responsive.css" rel="stylesheet" type="text/css" />

    <!-- custom javascript -->
    <script src="js/script.js" type="text/javascript"></script>

</head>
<body>

    <section class="py-3 bg-light">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                <li class="breadcrumb-item">@Html.ActionLink("Danh mục sản phẩm", "Index", "Products")</li>
                <li class="breadcrumb-item">@Html.ActionLink(Model.Brand.Name, "GetProducts/" + Model.BrandId, "Products")</li>
                <li class="breadcrumb-item">@Model.Name</li>

            </ol>
        </div>
    </section>

    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content bg-white padding-y">
        <div class="container">

            <!-- ============================ ITEM DETAIL ======================== -->
            <div class="row">
                    <aside class="col-md-6">
                        <div class="card">
                            <article class="gallery-wrap">
                                <div class="img-big-wrap">
                                    <div> <a href="#" ><img src="~/Content/images/items/@Model.Avartar"></a></div>
                                </div> <!-- slider-product.// -->
                                <div class="thumbs-wrap">
                                    <a href="#" class="item-thumb thumb-main"> <img src="~/Content/images/items/@Model.Avartar"></a>
                                    <a href="#" class="item-thumb thumb-main"> <img src="~/Content/images/items/@Model.Avartar1"></a>
                                    <a href="#" class="item-thumb thumb-main"> <img src="~/Content/images/items/@Model.Avartar2"></a>
                                    <a href="#" class="item-thumb thumb-main"> <img src="~/Content/images/items/@Model.Avartar3"></a>
                                </div> <!-- slider-nav.// -->
                            </article> <!-- gallery-wrap .end// -->
                        </div> <!-- card.// -->
                    </aside>
                    <main class="col-md-6">
                        <article class="product-info-aside">

                            <h2 class="title mt-3">@Model.Name </h2>

                            <div class="rating-wrap my-3">
                                <ul class="rating-stars">
                                    <li style="width:80%" class="stars-active">
                                        <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    </li>
                                    <li>
                                        <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    </li>
                                </ul>
               
                            </div> <!-- rating-wrap.// -->

                            <div class="mb-3">
                                <var class="price h4">  @string.Format("{0:0,0}", Model.Price) </var>
                                <span class="text-muted">Đ</span>
                            </div> <!-- price-detail-wrap .// -->

                            <p>
                                @Model.ShortDes
                            </p>


                            <dl class="row">
                                <dt class="col-sm-3">Hãng Sản Xuất</dt>
                                <dd class="col-sm-9"><a href="#">@Model.NCC.TenNCC</a></dd>

                                <dt class="col-sm-3">Tình Trạng</dt>
                                <dd class="col-sm-9">@Model.TinhTrang</dd>

                                <dt class="col-sm-3">Bảo hành</dt>
                                <dd class="col-sm-9">@Model.BaoHanh</dd>


                            </dl>

                            <div class="form-row  mt-4">
                                <div class="form-group col-md flex-grow-0">
                                    <div class="input-group mb-3 input-spinner">
                                        <input type="text" id="ipQuantity" class="form-control" value="1">
                                    </div>
                                </div> <!-- col.// -->
                                <div class="form-group col-md">
                                    <a href="#" id="addtocart" class="btn  btn-primary">
                                        <i class="fas fa-shopping-cart"></i>
                                        <span class="text" h>Thêm vào giỏ hàng</span>
                                    </a>
                                </div> <!-- col.// -->
                            </div> <!-- row.// -->

                        </article> <!-- product-info-aside .// -->
                    </main> <!-- col.// -->

            </div> <!-- row.// -->
            <!-- ================ ITEM DETAIL END .// ================= -->


        </div> <!-- container .//  -->
    </section>
    


</body>
</html>

DoAnLapTrinhWed-2/DoAnLapTrinhWed-2/Views/Products/GetBrand.cshtml
@model IEnumerable<DoAnLapTrinhWed_2.Models.Brand>

@foreach (var item in Model)
{
    <li>@Html.ActionLink(item.Name, "GetProducts/" + item.BrandId, "Products")</li>
}